language: php

php:
    - 7.0
    - 7.1
    - 7.2


dist: trusty

before_script:
    - composer install --profile --prefer-source

script:
  - bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
